export const WRITER_RESPONSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "title",
    "titleCandidates",
    "titleSelectionReason",
    "metaDescription",
    "labels",
    "html",
    "factualNotes",
    "usedClaimIds",
    "coverageMap",
    "answerSummary",
    "valueAdd",
  ],
  properties: {
    title: { type: "string" },
    titleCandidates: {
      type: "array",
      minItems: 4,
      maxItems: 4,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "strategy", "queryFit", "promise", "risk"],
        properties: {
          title: { type: "string" },
          strategy: {
            type: "string",
            enum: [
              "direct_answer",
              "conditional",
              "comparison",
              "problem_solution",
            ],
          },
          queryFit: { type: "string" },
          promise: { type: "string" },
          risk: { type: "string" },
        },
      },
    },
    titleSelectionReason: { type: "string" },
    metaDescription: { type: "string" },
    labels: { type: "array", items: { type: "string" } },
    html: { type: "string" },
    factualNotes: { type: "array", items: { type: "string" } },
    usedClaimIds: { type: "array", items: { type: "string" } },
    coverageMap: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["requirement", "addressed", "location"],
        properties: {
          requirement: { type: "string" },
          addressed: { type: "boolean" },
          location: { type: "string" },
        },
      },
    },
    answerSummary: { type: "string" },
    valueAdd: {
      type: "object",
      additionalProperties: false,
      required: ["type", "description"],
      properties: {
        type: { type: "string" },
        description: { type: "string" },
      },
    },
  },
} as const;

export const REVIEW_RESPONSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "passed",
    "overallScore",
    "factualScore",
    "usefulnessScore",
    "styleScore",
    "intentScore",
    "evidenceScore",
    "originalValueScore",
    "readabilityScore",
    "titleAccuracyScore",
    "completenessScore",
    "titleAssessment",
    "issues",
    "correctedTitle",
    "correctedMetaDescription",
    "correctedHtml",
  ],
  properties: {
    passed: { type: "boolean" },
    overallScore: { type: "number" },
    factualScore: { type: "number" },
    usefulnessScore: { type: "number" },
    styleScore: { type: "number" },
    intentScore: { type: "number" },
    evidenceScore: { type: "number" },
    originalValueScore: { type: "number" },
    readabilityScore: { type: "number" },
    titleAccuracyScore: { type: "number" },
    completenessScore: { type: "number" },
    titleAssessment: {
      type: "object",
      additionalProperties: false,
      required: [
        "queryMatch",
        "specificity",
        "accuracy",
        "distinctiveness",
        "concision",
        "decision",
      ],
      properties: {
        queryMatch: { type: "number" },
        specificity: { type: "number" },
        accuracy: { type: "number" },
        distinctiveness: { type: "number" },
        concision: { type: "number" },
        decision: { type: "string" },
      },
    },
    issues: { type: "array", items: { type: "string" } },
    correctedTitle: { type: "string" },
    correctedMetaDescription: { type: "string" },
    correctedHtml: { type: "string" },
  },
} as const;
